# Generated by Django 4.1.3 on 2022-12-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED'), ('DIVORCED', 'DIVORCED')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Blood_Group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='', max_length=20),
        ),
    ]
