# Generated by Django 4.1.3 on 2022-12-12 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_remove_employee_martial_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='marital_status',
        ),
        migrations.AddField(
            model_name='employee',
            name='martial_Status',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='Blood_Group',
            field=models.CharField(max_length=100),
        ),
    ]
